export class Person {
          id: Number;
          userName:  String;
          fName:  String;
          mName: String;
          lName:  String;
          gender:  String;
          dob:  String ;
          tob:  String ;
          placeOfBirth:  String ;
          qualification:  String ;
          religion:  String ;
          cast:  String ;
          gotra:  String ;
          gotraToSave:  String ;
          nameOfCollage:  String ;
          income: Number;
          familyIncome: Number;
          city:  String ;
          noOfSisters: Number;
          noOfBrother: Number;
          height:  Number ;
          bodyType:  String ;
          complexion:  String ;
          challenged:  String ;
          primeryContactNo:  Number ;
          secoundryContactNo: Number;
          personStatus: String;
          profilePic: String;
          maritalStatus:  String;
}
